version: "3.9"

services:
  subapis_service:
    build: .
    image: sub-api-dashboard
    container_name: sub-api-dashboard
    ports:
      - "5040:5040"
    volumes:
      - .:/app
    restart: always